import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/app/navbar";
import Sidebar from "@/app/sidebar"; // Import your sidebar component

// Import custom fonts
const geistSans = localFont({
  src: "./fonts/Calibri-Bold.woff",
  variable: "--font-geist-sans", // Set a CSS variable for GeistSans
  weight: "100 900", // Variable weight support
});

const geistMono = localFont({
  src: "./fonts/Calibri-Bold.woff",
  variable: "--font-Calibri-Bold", // Set a CSS variable for GeistMono
  weight: "100 900", // Variable weight support
});

// Metadata for SEO
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout function
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Applying both fonts as CSS variables globally
      >
        {/* Main Layout structure */}
        <div className="min-h-screen bg-[url('https://s3-alpha-sig.figma.com/img/850e/4153/42a513e4e1c22278a91fcee8c0e476ae?Expires=1730073600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=owuqroqOobdlQ6qtuDurx4yqUDreCW0ELIGqDIzKyvAaLgrUUyDXh2mWGxxxQ1YU9SwIVxsPQ9HEJC7KhdBGlrERWD9WyQoFAQv5UF~if9yz5ymywbRB-PvFZcDsl5Jv8UazH2jx3q8ThtolX6GzI-jt8HTZd5rSFZPYF2Zsgzfz2~S6GSZHhZokYCNSc1l0t370q5CRJXrHUjtf6oOH8WZTP5s3CeAt9Ezql-N8Yh4Ui~LMRGGfCwNhmQXn4BfT4oZJBNN8kt2vcB-7elPST9bQgOju2~RTuYU2GeWkmx8ppy76bAwtn7M65rkM6O8sETq3SHCF5aWn4IeQsljZBA__')]  xs:bg-cover :bg-contain flex flex-row">
         
          {/* Main Content Area */}
          <div className="flex space-x-3 flex-col flex-grow">
            <header className="bg-none text-white p-4">
              <NavBar />
            </header>

            <main className="flex space-x-8 mx-auto p-2">
              <Sidebar/>
              {children} {/* Children components will render here */}
            </main>

            {/* Footer Component */}
            {/* <footer className="bg-none text-white text-center p-4">
              <p>&copy; {new Date().getFullYear()} Your Company</p>
            </footer> */}
          </div>
        </div>
      </body>
    </html>
  );
}
