import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/app/navbar";
import Sidebar from "@/app/sidebar"; // Import your sidebar component

// Import custom fonts
const geistSans = localFont({
  src: "./fonts/Calibri-Bold.woff",
  variable: "--font-geist-sans", // Set a CSS variable for GeistSans
  weight: "100 900", // Variable weight support
});

const geistMono = localFont({
  src: "./fonts/Calibri-Bold.woff",
  variable: "--font-Calibri-Bold", // Set a CSS variable for GeistMono
  weight: "100 900", // Variable weight support
});

// Metadata for SEO
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout function
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Applying both fonts as CSS variables globally
      >
        {/* Main Layout structure */}
        <div className="min-h-screen bg-[url('/bg.svg')]  xs:bg-cover :bg-contain flex flex-row">
         
          {/* Main Content Area */}
          <div className="flex space-x-3 flex-col flex-grow">
            <header className="bg-none text-white p-4">
              <NavBar />
            </header>

            <main className="flex space-x-8 mx-auto p-2">
              <Sidebar/>
              {children} {/* Children components will render here */}
            </main>

            {/* Footer Component */}
            {/* <footer className="bg-none text-white text-center p-4">
              <p>&copy; {new Date().getFullYear()} Your Company</p>
            </footer> */}
          </div>
        </div>
      </body>
    </html>
  );
}
